[package]
name = "fix-nonsteam-game-artwork"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
dialoguer = "0.10.4"
dirs = "5.0.1"
lazy_static = "1.4.0"
regex = "1.9.3"
reqwest = { version = "0.11.18", features = ["blocking"] }
